package com.zorba.model;

import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

@Entity
@Table (name="customer")
public class Customer {
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "cust_id")
	private int custId;
	
	@Column(name = "cust_name")
	private String custName;
	
	@Column(name = "mobile_no")
	private String mob;
	
	@Column(name = "email")
	private String email;
	
	@Column(name = "driving_license")
	private String drivingLicense;
	
	@Column(name = "duration_Of_rent")
	private int durationForRent;
		
	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@JoinTable(name ="Customer_Vehicle_JoinTable",
      			joinColumns ={@JoinColumn(name = "Cutomer bata ayeko ID")},
      			inverseJoinColumns = {@JoinColumn(name ="Vehicle bata ayeko ID")})
	private List<Vehicle> vehicles;
		
	int rateOfVehicle;
	
	public List<Vehicle> getVehicles() {
		return vehicles;
	}

	public void setVehicles(List<Vehicle> vehicles) {
		this.vehicles = vehicles;
	}

	public Customer() {

	}

	public int getRateOfthevehicle() {
		return rateOfVehicle;
	}

	public void setRateOfthevehicle(int rateOfthevehicle) {
		this.rateOfVehicle = rateOfthevehicle;
	}


	public int getCustId() {
		return custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	//This is not necessary because the customer ID is autogenerated
//	public void setCustId(int custId) {
//		this.custId = custId;
//	}
	public String getCustName() {
		return custName;
	}
	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getMob() {
		return mob;
	}

	public void setMob(String mob) {
		this.mob = mob;
	}

	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getDrivingLicense() {
		return drivingLicense;
	}
	public void setDrivingLicense(String drivingLicense) {
		this.drivingLicense = drivingLicense;
	}
	public int getDurationForRent() {
		return durationForRent;
	}
	public void setDurationForRent(int durationForRent) {
		this.durationForRent = durationForRent;
	}
		

}
